import "./src/components/pilotosComponent.js";
import "./src/components/vehiculoComponent.js";
import  "./src/components/Iniciocomponent.js";
import "./src/components/menucomponent.js";
import "./src/components/autorscomponents.js";
import "./src/components/menucomponent.js"
import "./src/components/admPilotosComponent.js";
import "./src/components/adminIndexComponent.js"
import "./src/components/tablaComponent.js"